### ISSUE TITLE
(IOError) Operation not permitted exception crashes the plugin

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-output-udp#11]
Upon a `(IOError) Operation not permitted exception` by the socket send method per 

https://github.com/logstash-plugins/logstash-output-udp/blob/5ce21fbed852ea8c0a382e80a2bbb9852638357f/lib/logstash/outputs/udp.rb#L24

the plugin dies. 

The reason the underlying Java UDP socket write result in a `(IOError) Operation not permitted` exception is unclear, but it seems like a "normal" behaviour of the Linux kernel if a UDP socket is sending too fast.

I suggest we add a retry policy for this exception.

**Comment by MorrieAtElastic** [comment]
Customer in the SDH referenced above indicates this is a significant problem for him and wants to know if we can get a code fix for this problem in a reasonable timeframe.

**Comment by willemdh** [comment]
We run into this issue when we reload firewalld on our Logstash nodes. The result is that Logstash crashes, which is not good on PR Logstash nodes, as firewalld needs to be reloaded a lot as Logstash has no builtin ip filters..

**Comment by colinsurprenant** [comment]
@willemdh #12 should address your issue; logstash will not crash but drop+log the failed event upon socket write failure. You will also be able to specify a retry count and delay.

**Comment by colinsurprenant** [comment]
udp output v3.1.0 has been published.
