### ISSUE TITLE
Support for DTLS

### ISSUE THREAD

**Issue by eperry** [logstash-plugins/logstash-output-udp#7]
https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security

Would it be possible to request the next enhancement to support DTLS or any other type of SSL/TLS implementation?  

We are sending data over the internet or WAN and like the performance of UDP but since logstash udp does not support it at this time, we have to use TCP.    

I will see if I have time to add it to the project but, if anyone more experienced them me, It would be great to have in this ever increasing complex and insecure Internet World.

Thanks

**Comment by jordansissel** [comment]
I would prefer DTLS be a new input plugin, since DTLS (and TLS like TCP input has, and I regret adding due to complexity) requires some additional complexity in configuration that only impacts DTLS/TLS users. For this reason of avoiding added sometimes-optional complex configuration settings, I would prefer a DTLS feature be available in a new input plugin.

**Comment by eperry** [comment]
I understand your comment about making the code more complex, but slowly everything is becoming SSL/tls etc because of hacking. I personally think we should only have one, but since I am only proposing the enhancement and not writing the code. I will default to your preference. Maybe it will be a good spring exercise for me to learn more.

The reason I was asking for this, is that I am sending all my syslog data to a central server over the WAN. it occurred to me. That any good hacker could utilize that info to more easily hack a system. Of course I could move to tcp but that has performance issues over the WAN.

**Comment by jordansissel** [comment]
Thanks for the feedback :)

We may make a new DTLS input plugin someday, but if anyone wishes to work on in the meantime, I certainly encourage it.
