### ISSUE TITLE
Source IP spoofing capabilities

### ISSUE THREAD

**Issue by alesnav** [logstash-plugins/logstash-output-udp#8]
Hello there!

It would be nice if there was a possibility to change the Source IP of the UDP packet. This was asked in https://github.com/elastic/logstash/issues/4715 but I think that here would be the best place.

~~I think that this enhancement does already exist on Logstash Syslog Output plugin (https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html#plugins-outputs-syslog-sourcehost), so maybe it is not so hard to implement in this other plugin.~~

This enhancement will allow to re-send UDP events to a final destination, but saying that the sender is the original one. This deployment would be similar to:

1.- Original log source sends data to Logstash UDP input
2.- Logstash filters drop some events and lets the others continue.
3.- Filtered data will be sent to the final destination using Logstash UDP Output, but showing the original IP address in the Source IP header of the TCP/IP packet.

Thanks,
Best regards

EDIT: `sourcehost` parameter [Logstash Syslog Output plugin](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html#plugins-outputs-syslog-sourcehost) is not related to UDP spoofing. It only change the `hostname` in the syslog header inside payload.

**Comment by alesnav** [comment]
I did some investigations regarding UDP spoofing in Ruby and found [this opensource Metasploit plugin](https://github.com/pwnwiki/q/blob/master/modules/auxiliary/unstable/syslog_spoof_custom_message.rb) which makes it possible by using a class called `PacketFu`.

```
pkt = PacketFu::UDPPacket.new
pkt.udp_sport= rand(0xffff-1024) + 1024
pkt.udp_dport=dport.to_i
pkt.ip_saddr=sip
pkt.ip_daddr=ip
pkt.payload << gen_payload(sip)
pkt.recalc
```

I don't know if it is fine to use this class here or not. Anyway, I will test it making a new plugin based in this one and adding this functionality.

Thanks!

**Comment by simonclausen** [comment]
This would be great to have in the cases where some system expects "syslog" directly from source devices to function. And then won't deal with exporting logs, so they can also be used by others.

**Comment by davewat** [comment]
> I did some investigations regarding UDP spoofing in Ruby and found [this opensource Metasploit plugin](https://github.com/pwnwiki/q/blob/master/modules/auxiliary/unstable/syslog_spoof_custom_message.rb) which makes it possible by using a class called `PacketFu`.
> 
> ```
> pkt = PacketFu::UDPPacket.new
> pkt.udp_sport= rand(0xffff-1024) + 1024
> pkt.udp_dport=dport.to_i
> pkt.ip_saddr=sip
> pkt.ip_daddr=ip
> pkt.payload << gen_payload(sip)
> pkt.recalc
> ```
> 
> I don't know if it is fine to use this class here or not. Anyway, I will test it making a new plugin based in this one and adding this functionality.
> 
> Thanks!

@alesnav Did you ever make any progress building a new plugin to spoof the source?  Our SIEM requires the syslog event to arrive from the original source, which this would solve.

Thanks!

**Comment by xucito** [comment]
So I am looking at this currently,

**Comment by xucito** [comment]
So I am looking at this currently and it is looking grim,

Unfortunately the methodology above suggested by @alesnav won't work as **packetfu** is reliant on **pcaprub** which does not have a JRuby compatible implementation.

Actually any methodology that relies on a raw sockets will fail as [JRuby ](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/socket/RubySocket.java) does not implement the SOCK_RAW compatible implementation.

I am still exploring this so will update if I find something that can be natively used in a Logstash output plugin.

**Comment by xucito** [comment]
I have written a separate plugin to spoof IP and MAC Address for udp output.
https://github.com/xucito/logstash-output-spoof

It uses the jnetpcap library.

I think this can be closed on this issue, it is not possible using JRuby within this output plugin.

**Comment by colinsurprenant** [comment]
Thanks @xucito for looking into it. Closing.
